defaults: &defaults
  app_name: challenge
  domain: challenge.dev
  description:
  keywords:
  google_analytics_key:
  default_logo_url: "/images/logo.png"
  email_sender: ""
  facebook_app_id: 826576557376414
  facebook_secret: cb96375203f85418f1de0a37bf5a828e

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults