defaults: &defaults
  app_name: challenge
  domain: challenge.dev
  description:
  keywords:
  google_analytics_key:
  default_logo_url: "/images/logo.png"
  email_sender: ""
  facebook_app_id:
  facebook_secret:

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults