# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c59e2071f955bd86f011875aca69fff4a54c34d0cf9f31209d3265e90737e8662dfd61e92e22b580e1d71e1460fe57b9666702e360caf4cf93e60786fbe6f094

test:
  secret_key_base: 14a9260a0cfcc888b9ad572e53475062c63ed6bd6dfd4b2a13a2bcbff442232e63e5223357b5c3ed898869c279d602714e19b77ec9e50f88e2e41e0588bbda33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 14a9260a0cfcc888b9ad572e53475062c63ed6bd6dfd4b2a13a2bcbff442232e63e5223357b5c3ed898869c279d602714e19b77ec9e50f88e2e41e0588bbda33
